using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FnD.Cloud.API.Models;

public class CloudOrder
{
    [Key]
    public int Id { get; set; }

    // We store the ID generated by your friend's local SQLite DB for reference
    public int LocalOrderId { get; set; }

    public DateTime OrderDate { get; set; }

    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalAmount { get; set; }

    // Timestamp of when it actually hit your cloud server
    public DateTime SyncedAt { get; set; } = DateTime.UtcNow;

    // Navigation property for the items in this order
    public List<CloudOrderItem> Items { get; set; } = new();

    public string TenantId { get; set; } = string.Empty; // ◄ THE NEW SHIELD
}

public class CloudOrderItem
{
    [Key]
    public int Id { get; set; }

    public int CloudOrderId { get; set; }
    public CloudOrder Order { get; set; } = null!; // EF Core relationship

    public int ProductId { get; set; }
    public int Quantity { get; set; }

    [Column(TypeName = "decimal(18,2)")]
    public decimal UnitPrice { get; set; }
}